# -*- coding: utf-8 -*-
"""Datos_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jsb8Q0cJdyvF3CCI7TG8_k0kMOK_xCeY
"""

#Importar las librerias necesarias
import requests
import pandas as pd
import json
from datetime import datetime, timedelta

#Consumimos la API usando response
url='https://rickandmortyapi.com/api/character'
response=requests.get(url)

#Abrimos el archivo json y lo convertimos en un dataframe usando pandas
data= response.json()
df = pd.json_normalize(data)

#Vemos la información de nuesto dataframe
print(df.info())
print(df)
#Vemos que nuestro dataframe tiene 5 columnas con un registro cada una
#Una de ellas contiene otro JSON, otra un conteo de 826 personajes, otra un conteo de 42 paginas, otra nos dice la página siguiente y otro la previa
#Podemos descartar 4 de ellas porque no muestran información relevante para analizar
#Nos quedaremos con la que contiene el JSON porque es la que contiene infromación relevante sobre los personajes y lo abrimos
df1=pd.json_normalize(data["results"])

#Obtenemos información de nuestro nuevo dataframe
print(df1.info())
#Vemos que tenemos 14 columnas y 20 filas ninguna vacía

#Exploramos las columnas
print(df1["name"].unique())
print(df1["type"].unique())
print(df1["gender"].unique())
print(df1["origin.url"].unique())
print(df1["location.name"].unique())
print(df1["location.url"].unique())

#Sin embargo algunos campos tienen "" en type, así que reemplazamos esos datos por un "Without type"
df1["type"]=df1["type"].replace("","Without type")

#Algunos datos son "unknow" los transformaremos a "Unknow" para que sea como el resto de datos con la primera letra mayuscula
df1=df1.replace("unknown","Unknow")

#Los datos de nuestra columna episode son listas
#usamos la funcion explode para convertir cada elemento de la lista de episode en una fila
df1=df1.explode("episode")

#La columna "created" es una columna que contiene fechas, así cambiamos el tipo de dato a fecha
df1.created=pd.to_datetime(df1.created)

#Sustituimos los valores vacíos de "origin.url" con "Without URL"
df1["origin.url"]=df1["origin.url"].replace("","Without URL")

#De igual forma para "location.url"
df1["location.url"]=df1["location.url"].replace("","Without location")

#Finalmente renombramos nuestras columnas
df1=df1.rename(columns={"id":"ID","name":"Name","status":"Status","species":"Specie",
                        "type":"Type","image":"Image","episode":"Appearance_episode","url":"URL",
                        "created":"Created_date","origin.name":"Origin","origin.url":"Origin_URL",
                        "location.name":"Location","location.url":"Location_URL", "gender":"Gender"
})

#Y usamos como índice el ID
df1=df1.set_index("ID")